demo: 
  title: myorder
server:
  port: 8080
  context-path: /my.order
spring:
  application:
    name: my.order  
  datasource:  
    driver-class-name: com.mysql.jdbc.Driver
    url: 'jdbc:mysql://192.168.169.128:3306/order?useUnicode=true&characterEncoding=utf8'  
    username: root 
    password: 123456
    continue-on-error: true  
    tomcat.max-wait: 1000  
    tomcat.test-on-borrow: true  
    hikari:
      maximum-pool-size: 10
  data:
    cassandra:
      read-timeout-millis: 5000
  jpa:  
    show-sql: true
mybatis: 
    typeHandlersPackage: com.order.dao.*
    typeAliasesPackage: com.order.model.*
    mapperLocations: classpath:mybatis/mapper/*.xml
    checkConfigLocation: true
 