demo: 
  title: myorder
server:
  port: 8081
  context-path: /my.order
spring:
  application:
    name: my.order  
  datasource:  
    driver-class-name: com.mysql.jdbc.Driver
    url: 'jdbc:mysql://192.168.169.128:3306/order_form?useUnicode=true&characterEncoding=utf8'  
    username: root 
    password: 111111
    continue-on-error: true  
    tomcat.max-wait: 1000  
    tomcat.test-on-borrow: true  
    hikari:
      maximum-pool-size: 10
  data:
    cassandra:
      read-timeout-millis: 5000
  jpa:  
    show-sql: true
mybatis-plus: 
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #配置显示sql
    map-underscore-to-camel-case: false #字段是否有_设置 
  global-config:
    #meta-object-handler: com.MybatisObjectHandler
    db-config:
      id-type: auto #默认主键类型
      logic-not-delete-value: 0 
      logic-delete-value: 1
      table-underline: false #表名是否有_  可以通过@TableName("")指定数据表名称
feign: 
    httpclient:
      time-to-live: 50000
    client:
      config:
        feignName:
           read-timeout: 5000
           connect-timeout: 5000  
 
